######################################################################
#
# Build and run the test framework.
# 
# For now, assume that the library has been built, and is still
# installed locally.

compiled:
	ghc --make QC.hs -o qc
